### ISSUE TITLE
Bug: Linear+Polygon constraint return invalid bounds

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#10]
Method IConstraint::getBounds  not used in project. But for both implementations Linear+Polygon returns invalid value. Bounds always covers coordinate x=0, y=0.

  private final Rectangle2D bounds = new Rectangle2D.Double();
- x=0, y=0, w=0, h=0
- Rectangle2D:add don't check whether Rectangle2D is initialized with valid coordinate.

Suggested fix:
  public void add(Vertex v) {
    if (v.getX() == x && v.getY() == y) {
      return;  // ignore duplicate points
    }
    v.setConstraintMember(true);
    x = v.getX();
    y = v.getY();
    if (list.isEmpty())
        bounds.setRect(v.getX(), v.getY(), 0.0, 0.0);
    else
        bounds.add(v.getX(), v.getY());
    list.add(v);
  }

**Comment by gwlucastrig** [comment]
Thank you for finding that!   I'll integrate a change into the code the next time I update it.

**Comment by gwlucastrig** [comment]
The bug you identified was fixed and the code was updated.  Thank you for your contribution.
