### ISSUE TITLE
RFE: increase QuadEdge.CONSTRAINT_INDEX_MAX to 2^24

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#12]
I suggest to increase CONSTRAINT_INDEX_MAX to 2^24. Current value is 2^20.
```
  /**
   * The maximum value of a constraint index based in space
   * allocated for its storage. This is a value of (2^24-1).
   * In practice this value is larger than the available
   * memory on many contemporary computers would allow.
  */
  public static final int CONSTRAINT_INDEX_MAX = 1 << 24;

  /**
   * A mask that can be anded with the QuadEdgePartner's
   * index field to extract the constraint index,
   * equivalent to the 20 low-order bits.
   */
  public static final int CONSTRAINT_INDEX_MASK = CONSTRAINT_INDEX_MAX - 1;
```

**Comment by gwlucastrig** [comment]
This might just be an issue of the Javadoc not matching the code.  I will have to look at that.

I will also review this issue.  I have 32 bits that I can use without increasing the memory size for the QuadEdge classes.  I need at least a few to indicate constraint status.  Those I don't use can be used for the constraint index.  I wasn't sure how many bits I wanted to reserve for future use.  Eight might be enough.  If so, that leaves 24 for the max constraint index.  20 was a conservative value, but I think I might be able to reallocate it to 24.

**Comment by gwlucastrig** [comment]
The proposed change was integrated into code.  Thank you for your contribution.
