### ISSUE TITLE
Perf: SemiVirtualIncrementalTin::processConstraint set 'searchEdge'. Correct?

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#13]
I've improved SemiVirtualIncrementalTin::processConstraint with setting `searchEdge=e0` at last line of method.
Is it correct? I don't experience any issues.

I use modified Hilbert Sort for constraint sort. I'm sorting by first vertex of constraint.

My test data set:
Vertex: ~80M - non unique
Constraint: 1.8M - all polygons, every vertex is member of polygon
Time to finish: under 6 minutes

**Comment by gwlucastrig** [comment]
You change makes sense.  I will have to review the code to be sure.

Did you really manage to get Tinfour to accept 80 million vertices?   Wow!   I am impressed.

I saw a paper the other day that might have some relevance to the problem you are working on.  It's called [Streaming Computation of Delaunay Triangulations](https://people.eecs.berkeley.edu/~jrs/papers/dtstream.pdf).  Two of the authors, Martin Isenburg and Jonathan Shewchuk have made major contributions to the technology of Delaunay triangulations.

**Comment by gwlucastrig** [comment]
The proposed change was integrated into code.  Thank you for your contribution.
