### ISSUE TITLE
NPE: processing polygon constraint from #15

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#17]
Separate issue for NPE. Sample code is attached to #15 - Internal failure, constraint not added.
Please remove/comment data row with ID 26 as said in comment.

Sorry that I don't provide stack trace. I have modified version with custom debug information. So line numbers will not match.

**Comment by gwlucastrig** [comment]
Thanks for the information.  This issue is addressed (and, I hope, answered) by recent code fixes for issue #15.   Therefore I am closing this issue.  Issue #15 will remain open pending further testing.
