### ISSUE TITLE
RFE: use Thresholds instead of nominalPointSpacing

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#21]
???StochasticLawsonsWalk
???Interpolator calls IIncrementalTin::getNominalPointSpacing
...
maybe it will be needed to add getThresholds to IIncrementalTin
Thresholds class is immutable so can be shared across all instances.

Class TriangleCount
Uses GeometricOperations with default Thresholds (nominalPointSpacing = 1.0). Maybe this is bug.

**Comment by gwlucastrig** [comment]
Good suggestion...  I just added getThresholds to the incremental TIN classes.  

The   TriangleCount class does not use any of the methods that depend on thresholds (inCircle, etc.) so it can use the generic GeometricOptions constructor.  There is, however, a chance that future versions of the class might add functionality that depends on these methods. So you're suggestion is well taken and I am adding that as well. 

Do you use the tabulateTriangle method in any of your work?  It's declared "public", but I think that was a mistake.  I'm going to make it private if you don't use it.

**Comment by jandam** [comment]
I don't use tabulateTriangle so you can make it private. Another method HilbertSort :: xy2Hilbert can be static.
