### ISSUE TITLE
RFE: add support for writing constrains

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#25]
There is already class ConstraintLoader.

```
    public static void writeConstraintFile(final Path path, final List<IConstraint> list) throws IOException {
        try (BufferedWriter w = Files.newBufferedWriter(path)) {
            for (IConstraint constraint : list) {
                List<Vertex> vertices = constraint.getVertices();
                w.write(String.format(Locale.ENGLISH, "%d\r\n", vertices.size()));
                for (Vertex vertex : vertices) {
                    w.write(String.format(Locale.ENGLISH, "%s,%s,%s\r\n", vertex.x, vertex.y, vertex.getZ()));
                }
            }
        }
    }

```

**Comment by gwlucastrig** [comment]
I can add this code to the vertex loader class.   Do you seen any value is also storing the vertex index?   
Would you like to include the constraint-type metadata (polygon versus line feature)?

**Comment by jandam** [comment]
Type metadata would be useful. Idea behind this extension to have format for reporting issues with TIN. I can simply attach file. And this format is already supported by Viewer.

**Comment by gwlucastrig** [comment]
A write method has been added based on Martin Jandam's code.  Testing this feature revealed an opportunity to improve the speed of the text-based constraint file reader.  The speed of reading files was improved by more than a factor of 10.  

This issue is now closed.
