### ISSUE TITLE
SemiVirtualEdgePage::deallocateEdge should reset constraint

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#28]
SemiVirtualEdgePage::deallocateEdge shoud reset constraint. Otherwise when edge is reused can have invalid constraint flags/index. I don't have test to reproduce this issue. Maybe cannot occur in current algorithm. But still should be fixed for correctness.

Missing following line:
`    if (constraints != null) constraints[offset >> 1] = 0;
`

**Comment by gwlucastrig** [comment]
Both of your observations are correct.

First, you are right about the code fix.  The current code needs to have that line added.  I will take of it next time I have an opportunity to work on Tinfour.  

Second, you are correct that the glitch does not affect the current implementation.  At present, Tinfour "locks" the collection and does not allow the TIN to be modified after constraints are added.  So constrained edges will never be removed and the deficiency never matters.  Nor can it be tested.

For future work, however, I am considering algorithms that require the ability to remove vertices from the TIN.  When vertices are removed, edges will also have to be removed or reused.  In that case, having the correct behavior on the deallocateEdge is critical to the algorithms success.  If you hadn't identified the problem, it eventually would have cost me a lot of unnecessary time debugging the issue.  So thanks.  

Gary


P.S. I must say that you are looking at my code very closely.  And you seem to be finding some very subtle issues...  I am grateful to have somebody doing that.

**Comment by gwlucastrig** [comment]
Correction made to code.  This issue is now closed.
