### ISSUE TITLE
Code cleanup: use tin.getThresholds() where possible

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#29]
Use tin.getThresholds() where possible. Some IDE has Find usages on constructor: Thresholds::Thresholds(final double nominalPointSpacing)

Usage found in constructors of following classes (not all listed):
SemiVirtualNeighborEdgeLocator
NeighborEdgeLocator
TriangularFacetInterpolator
NaturalNeighborInterpolator

Standard:
https://github.com/gwlucastrig/Tinfour/blob/2733639ec14360a848bd96ae7e2ac4eaeb6b90b4/src/main/java/tinfour/standard/IncrementalTin.java#L481
https://github.com/gwlucastrig/Tinfour/blob/2733639ec14360a848bd96ae7e2ac4eaeb6b90b4/src/main/java/tinfour/standard/IncrementalTin.java#L1619
https://github.com/gwlucastrig/Tinfour/blob/2733639ec14360a848bd96ae7e2ac4eaeb6b90b4/src/main/java/tinfour/standard/NeighborEdgeLocator.java#L56

**Comment by gwlucastrig** [comment]
Code clean up complete.  Thank you for your suggestion.
