### ISSUE TITLE
LogoCDT: TriangleCollector.visitTriangles - missing triangles

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#32]
There are missing triangles when I replace in LogoPanel TriangleCollector.visitTrianglesForConstrainedRegion with TriangleCollector.visitTriangles.

https://github.com/gwlucastrig/Tinfour/blob/48eb0bf2cc2ef0469699b01fa0c7b4cd107621ab/src/test/java/tinfour/test/examples/LogoPanel.java#L212

Reproducible with both TIN implementations.
![ss-cdt-visit-triangles](https://user-images.githubusercontent.com/7425758/33135494-d0d351fe-cfa2-11e7-8b3e-17e345679bd9.png)

**Comment by gwlucastrig** [comment]
Sorry.  I got too aggressive with optimizations.  

The problem has been addressed and code update is posted.  I am closing this issue.

**Comment by jandam** [comment]
Thank you. Fix is working.
