### ISSUE TITLE
NPE: TIN::addWithInsertOrAppend

### ISSUE THREAD

**Issue by jandam** [gwlucastrig/Tinfour#34]
NPE is thrown during adding vertices in both implementations (Incremental + SemiVirtual).

NPE is thrown at:
https://github.com/gwlucastrig/Tinfour/blob/cfd50eb7c63061b02598375695f47c83d51f98cd/src/main/java/tinfour/standard/IncrementalTin.java#L877

Code to reproduce:
```
        List<Vertex> vertexList = new ArrayList<>(9);

        vertexList.add(new Vertex(182.55700774327852, -44.80335783492774, Double.NaN, 1));
        vertexList.add(new Vertex(125.61337371205445, -45.553850029595196, Double.NaN, 2));
        vertexList.add(new Vertex(130.5337093362808, -4.28630821921659, Double.NaN, 3));
        vertexList.add(new Vertex(108.32916380139068, 13.0071487640962, Double.NaN, 4));
        vertexList.add(new Vertex(136.4296682029902, -8.87822886342019, Double.NaN, 5));
        vertexList.add(new Vertex(138.5582786850251, -10.536044095326556, Double.NaN, 6));
        vertexList.add(new Vertex(142.72869756363542, -13.78407091786698, Double.NaN, 7));
        vertexList.add(new Vertex(156.62775913006791, -24.609008673509535, Double.NaN, 8));
        vertexList.add(new Vertex(125.32986550155634, -11.496184864434124, Double.NaN, 9));
        
        IIncrementalTin tin = new IncrementalTin(1e-8);
        tin.add(vertexList, null);

```
Issue:
I think that problem is in bootstrap method that selects triangle with almost collinear edges. As can be seen on attached screenshot.
  Similar issue can be reproduced when TIN is bootrapped from vertices that are too close together. Such vertices will be merged to group in next step. Creating invalid TIN.

Proposed solution:
Add validity check to bootstrap method: Ignore degenerated triangles according to TIN thresholds.

Screenshot with edges (RED) after NPE is thrown. ORANGE = vertices.
![ss-tin-boot-npe](https://user-images.githubusercontent.com/7425758/37282983-9d05f87c-25f6-11e8-90af-349ea9c4bc68.png)

**Comment by jandam** [comment]
Workaround:
  Sort vertices by Hilbert sort. This is not working when some of vertices selected by bootstrap are merged to vertex group.

**Comment by gwlucastrig** [comment]
I am investigating.  One question:  The estimated point spacing value you pass into the constructor seems  small relative to the coordinates in the example.   What coordinate system are you working in?  Have you tried a larger value?

**Comment by gwlucastrig** [comment]
The failure occurs in multiple places throughout the processing sequence., but it begins with the bootstrap method picking a poor quality triangle as a start.  As a temporary measure, make a change to BootstrapUtility about line 84 where it tests on if(nTrial<1){nTrial=1;}    Raise the value from 1 to 8.    So if(nTrial<8){nTrial=8;}

**Comment by jandam** [comment]
Good point. I didn't try larger value. I will try it tomorrow. 
  I suppose that skipping random part of bootstrap and using second part will work correctly. Proper solution is to ignore all degenerated triangles. 

  I'm working on some kind of vertex snapper. It snaps near vertices, compute edge/segment intersections with given precision/treshold. It works with edge priority. The aim is to prepare geometries for Tinfour. Highest priority is used for outline - it means no change is allowed.

  I'm sorry that I didn't make complete report.


13. 3. 2018 v 20:30, gwlucastrig <notifications@github.com>:

**Comment by gwlucastrig** [comment]
Again, this is not a solution, but an temporary measure.  The following code shows an example of how to estimate point spacing... It's taken from the SingleBuildTest example.  In the case of the example code you posted, the estimated point spacing was about 19.3
 

` 
static double estimateSpacing(List<Vertex> vertexList) {

    if (vertexList.isEmpty()) {
      return Double.NaN;
    }

    double xMin = Double.POSITIVE_INFINITY;
    double yMin = Double.POSITIVE_INFINITY;
    double xMax = Double.NEGATIVE_INFINITY;
    double yMax = Double.NEGATIVE_INFINITY;

    for (Vertex v : vertexList) {
      double x = v.getX();
      double y = v.getY();
      if (x < xMin) {
        xMin = x;
      }
      if (x > xMax) {
        xMax = x;
      }
      if (y < yMin) {
        yMin = y;
      }
      if (y > yMax) {
        yMax = y;
      }
    }

    // estimate the point spacing.  The estimate is based on the simplifying
    // assumption that the points are arranged in a uniformly spaced
    // triangulated mesh (consisting of equilateral triangles). There would
    // be 3*N triangules of area s^2*sqrt(3)/4.
    double area = (xMax - xMin) * (yMax - yMin);
    double sSpace = 0.87738 * Math.sqrt(area / vertexList.size());
    if (sSpace == 0) {
      return Double.NaN;
    }
    return sSpace;

  }
`

**Comment by gwlucastrig** [comment]
There's  a deficiency in BootstrapUtility.  If the first part of the routine does not find an adequate triangle by using the random search, the second part should perform an exhaustive search.  But the threshold for determining whether a triangle is adequate would depend on the estimated point spacing of the input sample. I will be uploading a patch for this issue in the next couple of days.

**Comment by gwlucastrig** [comment]
I am now closing this issue.

I have posted code to make BootstrapUtility more robust.  The other half of this problem was that many things internal to the Incremental TIN classes depend on an approximately correct value for the estimated point spacing (at least correct to with a couple of orders of magnitude) to derive reasonable threshold values for its algorithms.  

There are some exact solutions to the computational geometry problems such as the inCircle calculation used by Tinfour.  I particularly admire the work of Jonathan Shewchuk.  For purposes of speed, Tinfour does not use these.  This design decision has a trade off because the code gains speed, but is less robust than it would otherwise be.

**Comment by jandam** [comment]
I think that triangleMinAreaThreshold should be used at BoostrapUtility:188 too. The line is reachable when n>=4 and all vertices lies on line. Similar case to n=3 that is fixed by your patch.

https://github.com/gwlucastrig/Tinfour/blob/2cb3f7b1d1eb233834140c5ed0e146bf2234f51a/src/main/java/tinfour/common/BootstrapUtility.java#L188

Thank you very much  for patch

**Comment by gwlucastrig** [comment]
The changes to BootstrapUtility are now turned in.
