### ISSUE TITLE
Some edges from getNeighborEdge() are not in Tin?

### ISSUE THREAD

**Issue by micycle1** [gwlucastrig/Tinfour#64]
I've noticed that some edges returned by the methods below are not in the list returned by `tin.getEdges()`. Is this expected?

- `tin.getNavigator().getNeighborEdge(x, y)`
- `tin.getNeighborEdgeLocator().getEdgeWithNearestVertex(x, y).getEdge()`

**Comment by micycle1** [comment]
Update: it seems those methods sometimes can return either half edges or base reference of such. It seems getEdges() return base edges only?

**Comment by gwlucastrig** [comment]
Your deduction is correct.  For the incremental TIN classes, the getEdges() method and the edges() methods only return references to the base edges.  There's a paragraph in the wiki [Turtorial Using Edge Based Techniques](https://github.com/gwlucastrig/Tinfour/wiki/Tutorial-Using-Edge-Based-Techniques-Part-1) that describes this:

        int nEdges = 0;
        for(IQuadEdge edge: tin.edges()) {  // main edge iterator loop
               System.out.format("Edge %4d %n", edge.getIndex()); 
               nEdges++;
        }

> The code above works just fine, but it only tells half the story. If you were to run it, the result would be
> a list of even numbers. Recall that a Tinfour edge is actually a pair of objects. As used in the code above,
> the loop only exposes one of the objects in the pair. So only the indices for the even-numbered side of
> the edges are output. 

The navigator and neighbor edge locator operations are used to find the side of an edge that faces a query point.  So they can return the odd-numbered, non-base edges.

**Comment by micycle1** [comment]
How would you advise getting all non-base edges from a Tin? How does one get both half-edges represented by a base edge: is it `getDualFromReverse()` and `getDual()`?

**Comment by gwlucastrig** [comment]
You could try something like the following. 

    for(IQuadEdge edge: tin.edges()) {  // main edge iterator loop
           System.out.format("Base Edge %4d %n", edge.getIndex());   // even number
           IQuadEdge dual = edge.getDual();
           System.out.format("Base Edge %4d %n", dual.getIndex());   // odd number
    }

The IQuadEdge instances always represent one side of an edge.  The dual is always the other side.  The getDual() method returns the other side, and it always returns a valid reference. So we see that:

    IQuadEdge   edge = [any old edge]
    IQuadEdge   dual  = edge.getDual();
    IQuadEdge   dualOfDual = dual.getDual();
    edge.equals(dualOfDual) is true.
