### ISSUE TITLE
ContourBuilderForTin doesn't like coordinates of zero

### ISSUE THREAD

**Issue by micycle1** [gwlucastrig/Tinfour#66]
When a `ContourBuilderForTin` is initialised with a vertices list where some vertices have 0 in either the x or y coordinate, the following error is returned. Fudging the coordinates by 0.0001 fixes the problem.

```
java.lang.NullPointerException: Cannot invoke "org.tinfour.contour.PerimeterLink.addContourTip(org.tinfour.contour.Contour, boolean)" because "pStart" is null
	at org.tinfour.contour.ContourBuilderForTin.buildRegionsUsingPerimeter(ContourBuilderForTin.java:701)
	at org.tinfour.contour.ContourBuilderForTin.buildRegions(ContourBuilderForTin.java:638)
	at org.tinfour.contour.ContourBuilderForTin.<init>(ContourBuilderForTin.java:253)
```

**Comment by gwlucastrig** [comment]
Thanks for bringing this issue to my attention.  It's a pretty strange bug.  I would have said that, to Tinfour, zero is just another coordinate.  I will look at it this evening.

Do you have a sense as to whether this happens for all input sets or if it is related to a particular set of input coordinates? In the later case, do you have a set of test coordinates I could use?

Also, is there any chance you could run your test program with assertions enabled?   I seldom use assertions in my code, but for the contouring implementation I felt that they were a necessary precaution.  In this case, they may help us catch a condition that I hadn't anticipated when I designed the contouring class.  If you run the Java JVM from the command line, you can enable assertions by adding the option -enableassertions.  From an IDE you can add the option to the runtime configuration.

**Comment by micycle1** [comment]
Looking at this further just now it doesn't seem that coordinate position is the exact cause.

For example, this causes the error:
```
ArrayList<Vertex> points = new ArrayList<>();
int spacing = 40;
for (int x = 0; x < width; x += spacing) {
	for (int y = 0; y < height; y += spacing) {
		points.add(new Vertex(x, y, sqrt(x * x + y * y)));
	}
}
```
Adjusting the z value by a little doesn't cause an error:
`points.add(new Vertex(x, y, sqrt(x * x + y * y) + 0.001));`

**Comment by gwlucastrig** [comment]
This will get me started...  By the time I was done with the class, I was sick of testing it....  Even so, I am willing to bet that I never tested with a regular grid.  What were your width and height settings?  And what did you supply to the TIN for a point-spacing parameter when your constructed it?  Also, what were the contour values you supplied?

**Comment by micycle1** [comment]
Spacing doesn't seem to matter, so let's say 10.
Tin point-spacing: 10.
Contour values:
`double[] intervals = generateDoubleSequence(0, 100, 10);`, where:
```
public static double[] generateDoubleSequence(double start, double end, double step) {
	double[] sequence = new double[(int) Math.ceil((end - start) / step)];
	for (int i = 0; i < sequence.length; i++) {
		sequence[i] = start + i * step;
	}
	return sequence;
}
```

Interestingly it crashes using `generateDoubleSequence(0, 100, 10)` but works with `generateDoubleSequence(0, 100, 0.1)`;

**Comment by gwlucastrig** [comment]
Hmmm.  It crashes with a contour interval of 10, but works with 0.1    This points to an interesting possibility.  In floating point numbers, there is no exact match for a value of 1/10th. So if you specify 0,1, you're actually getting something that's just a fraction off from 0.1.   So it is likely that none of your contour values are truly integral.  But all of your vertex Z values are integral values.  So this tells me that when you set the contour interval to 0.1, the contour values never quite match the values of the vertices in the TIN.

If a contour value exactly matches a Z value of a particular vertex, then it must pass through that vertex.  The contouring logic actually requires special handling for the case where a contour line passes exactly through a vertex. The case where it passes near a vertex is unambiguous, and easily handled).  The case where a contour line passes through a vertex is much harder and requires special logic for processing.  So it looks like there is something the special handling logic didn't quite cover.

This gives me a clue as to where I should look for the problem. Thanks for narrowing it down for me.  I'll keep you posted with regard to my progress.

**Comment by gwlucastrig** [comment]
I've narrowed this down to a minimal case, but don't have it working yet.  The problem occurs when a perimeter vertex has the exact z value of the contour.  Since this is a case I specifically tried to address in the code, I'm bit puzzled about went wrong.  Here's some sample code that causes the crash:
```
 public static void main(String[] args) {
    ArrayList<Vertex> points = new ArrayList<>();
    points.add(new Vertex( 0.0,  0.0,  0.0, 0));
    points.add(new Vertex( 0.0, 40.0, 40.0, 1));
    points.add(new Vertex(40.0,  0.0, 40.0, 2));
    points.add(new Vertex(40.0, 40.0, 56.6, 3));
    points.add(new Vertex(80.0,  0.0, 80.0, 4));
    points.add(new Vertex(80.0, 40.0, 89.4, 5));

    double[] zContour = new double[]{40.0};

    IIncrementalTin tin = new IncrementalTin(1.0);
    tin.add(points, null);

    ContourBuilderForTin builder = 
      new ContourBuilderForTin(tin, null, zContour, true);
  }
```

For what it's worth...  When trying to debug the contouring code, things are absolutely hopeless until you can narrow it down to a minimal case.

**Comment by gwlucastrig** [comment]
I just posted improvements to contouring to address this issue.  However, I've discovered some new special-cases that cause the contouring to fail.  So I am leaving this issue open and continuing work.

**Comment by gwlucastrig** [comment]
I basically have this fix completed.  I am doing some final clean up, adding some more comments and Javadoc, and will be submitting the final version soon.

The issue was related to the many special cases that can occur when contours are allowed to pass through vertices...  That is, when there exist vertices with the exact z values as a contour. I did quite a bit of rework on the code to address these situations.

I've attached an image created by contouring elevation data from a Lidar sample taken over Bear Mountain in Salisbury Connecticut.  Contours are drawn at 5 meter intervals ranging from 540 meters to 705 meters above mean sea level.

**Comment by gwlucastrig** [comment]
And here's an image created from the same vertices as the above, but with a more aggressive z-value smoothing applied.

![ContourLas05_MaxSmoothing](https://user-images.githubusercontent.com/19698145/115489083-93164080-a229-11eb-9628-8cf81380a4db.png)

**Comment by gwlucastrig** [comment]
It's been a long, rocky road, but this issue is now fully addressed.  Code is updated. A new unit test was introduced.

Thanks for finding this and bringing it to my attention.
