### ISSUE TITLE
TriangleCollector.visitTrianglesConstrained() visits triangles twice

### ISSUE THREAD

**Issue by micycle1** [gwlucastrig/Tinfour#77]
From what I can gather (based on summing triangle areas and then counting the number of calls to the consumers), `TriangleCollector.visitTrianglesConstrained()`, is calling the consumer twice for each triangle (when there are >1 constraints).

Summing area via constraints. This is correct:

```
double area = 0;
for (IConstraint constraint : tin.getConstraints()) {
	area+=((PolygonConstraint) constraint).getArea();								
}
```

```
Area of constraint 1: 379020
Area of constraint 2: -46430

Area Sum = 332590
```

Using `visitSimpleTriangles` (again, correct):
```
final ArrayList<Double> area = new ArrayList<>();
area.add(0d);
TriangleCollector.visitSimpleTriangles(tin, new Consumer<SimpleTriangle>() {
	@Override
	public void accept(SimpleTriangle t) {
		IConstraint constraint = t.getContainingRegion();
		if (constraint != null && constraint.definesConstrainedRegion()) {
			area.set(0, area.get(0) + t.getArea());
		}
	}
});
```

```
Area: 332590
```

Using `visitTrianglesConstrained` (**WRONG**):

```
Consumer<Vertex[]> triangleVertexConsumer = t -> {
	final double areaT = getAreaPrecise(t); // calls routine from SimpleTriangle.getArea()
	areaD.set(0, areaD.get(0)+areaT);
};
TriangleCollector.visitTrianglesConstrained(tin, triangleVertexConsumer);
```

```
Area: 665181
```

I then counted how many times each consumer is called. And indeed, `visitTrianglesConstrained` is called exactly twice the amount: 5276 times versus 2638 times (must be called twice per vertex triplet, since area is exactly double too).

---

This is the triangulation (has two constraints: the concave boundary and the hole):
![image](https://user-images.githubusercontent.com/9304234/121078300-ad53b000-c7d0-11eb-9c80-4c64ef8da560.png)

**Comment by gwlucastrig** [comment]
Thanks.

I'm looking at the code for visitTriangleConstrained and I cannot imagine
what I was thinking...

Gary

**Comment by gwlucastrig** [comment]
I've been tied up all month, but am looking at this now.  So far, I am unable to duplicate the problem.  On the other hand, the code for this module is a serious mess.  Also, it can be significantly reduced in complexity due to the introduction of the SimpleTriangle iterator operation now implemented in the incremental TIN classes.

My intention is to revamp the existing code and post it.  I will also try to come up with a JUnit test (I am phasing in JUnit tests for cases like this, where a simple, self-contained unit test is both feasible and meaningful).   Once I post an update, I'll let you know.

**Comment by gwlucastrig** [comment]
I have posted a fix to Issue 77.   I have a test application that I am using which I will refactor into a JUnit test.  Once the test is posted, I plan to close this issue.

In the mean time, if you find a problem with the update, please let me know.

**Comment by micycle1** [comment]
Good to hear!

**Comment by gwlucastrig** [comment]
A Junit test named TriangleCollectorConstraintTest has been added to verify the code changes for this issue.

This issue is now closed.

Thank you very much for identifying this problem.
