### ISSUE TITLE
Should `.visitTrianglesConstrained()` generate triangles for TINs with no constraints?

### ISSUE THREAD

**Issue by micycle1** [gwlucastrig/Tinfour#79]
This is not a bug but more a point of contention with the design.

`.visitTrianglesConstrained()` doesn't return any triangles for when a tin has no constraints. I think it's suitable to consider a TIN with no constraints as one where everything everything is included in a single constraint, in which case `.visitTrianglesConstrained()` would behave as `.visitTriangles()` does when applied to TINs with no constraints.

Either way, including a note in the Javadocs would be useful.

**Comment by gwlucastrig** [comment]
Thanks.  That's a good observation and a tricky point.

I'm sorry to say that visitTrianglesConstrained() is not the most
successful API I ever designed.  In particular, it provides the calling
application with vertices, but doesn't give the application any reference
back to the triangle from which the vertices are taken.  So the application
has no way of determining whether the vertices it presents belonged to a
constrained triangle or just an ordinary triangle.  So the only way to
ensure that the application knows what kind of triangle it is receiving is
to only give it one kind of triangle.  In other words, I think it would
have to limit its survey to constrained triangles.

You are absolutely right, though, that the Javadoc needs improvement.    I
will fix it next time I do a code drop.

I've got to say that I am both grateful to you for bringing these things to
my attention and impressed by the way you keep finding them.  It is good to
know that my code is receiving such careful attention.

Gary

**Comment by gwlucastrig** [comment]
I have updated the Javadoc to clarify this behavior.  Thank you for identifying this issue.

This issue is now closed.
