### ISSUE TITLE
Can't open recent LAZ files

### ISSUE THREAD

**Issue by zdila** [gwlucastrig/Tinfour#89]
I can't open some LAZ files and I must first uncompress them with `laszip` tool. Error I am getting:

```
ERROR: compressor 3 not supported (LASzip v2.4r1)
       please upgrade to the latest release of LAStools (with LASzip)
       or contact 'martin.isenburg@rapidlasso.com' for assistance.
ERROR: cannot open lasreaderlas with file name '/home/martin/fm/Tinfour/tile_-235000_-1227000.laz'
java.lang.NullPointerException: Cannot invoke "com.github.mreutegg.laszip4j.laslib.LASreader.inside_none()" because "reader" is null
	at com.github.mreutegg.laszip4j.LASReader$None.apply(LASReader.java:160)
	at com.github.mreutegg.laszip4j.LASReader.openReader(LASReader.java:108)
	at com.github.mreutegg.laszip4j.LASReader.access$100(LASReader.java:32)
	at com.github.mreutegg.laszip4j.LASReader$LASPointIterator.<init>(LASReader.java:116)
	at com.github.mreutegg.laszip4j.LASReader$LASPointIterator.<init>(LASReader.java:112)
	at com.github.mreutegg.laszip4j.LASReader.lambda$getPoints$3(LASReader.java:88)
	at org.tinfour.gis.utils.VertexReaderLaz.loadVertices(VertexReaderLaz.java:90)
	at org.tinfour.gis.utils.VertexReaderLas.read(VertexReaderLas.java:147)
	at org.tinfour.demo.viewer.backplane.ModelFromLas.load(ModelFromLas.java:142)
	at org.tinfour.demo.viewer.backplane.MvTaskLoad.run(MvTaskLoad.java:70)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by gwlucastrig** [comment]
Thank you for the sample.  It helped me identify the problem.  Unfortunately, I have bad news.

Tinfour reads LAZ (compressed LAS) files using a 3rd-party API called https://github.com/mreutegg/laszip4j.  There is a bug in the API that causes it to throw a NullPointerException when reading your file.   
 
I am going to post an issue in the laszip4j project.  They are an active project and may be able to find a solution fairly quickly.

Will your shared sample file remain available?

**Comment by zdila** [comment]
Thanks for the investigation. I will keep that file available for at least couple of months.

**Comment by gwlucastrig** [comment]
The Marcel Reutegger from the laszip4j project fixed the issue with their zip-reader library.  If you download and build his latest code, and configure the Tinfour viewer to use laszip4j-0.12-SNAPSHOT.jar your LAZ file.  I've attached a picture from the TinfourViewer showing a subsection of your data file.

I am going to leave this issue open in Tinfour for a few days to see if there are any new developments.  But based on the currently available information, I think it is ready to be closed.

![Issue89](https://user-images.githubusercontent.com/19698145/195728561-719c9c5d-152a-4d26-9119-5d72f36d9e0e.png)

**Comment by zdila** [comment]
Thank you! I've updated the dependency of `laszip4j` from 0.7 to 0.11 and now it reads correctly all my files (which also confirms a fix for #90). Just wondering why the version in [`pom.xml`](https://github.com/gwlucastrig/Tinfour/blob/707a3b3715e84220067fff4f505b0b37b927db0c/gis/pom.xml#L24) is still 0.7 and not 0.11.

**Comment by gwlucastrig** [comment]
The laszip4j developers have not yet pushed out their 0.11 version to the Maven Central Repository.  The latest version is 0.10.  So maven can't do an automatic build with 0.10.   I suspect that they will push out the new version fairly soon.  When they do, I will update my pom.xml.

**Comment by micycle1** [comment]
Seems to be available https://search.maven.org/artifact/com.github.mreutegg/laszip4j/0.11/jar

**Comment by gwlucastrig** [comment]
Thanks Michael.  I didn't think to look at Sonotype's website. It usually
takes 48 hours for updates to propagate to some of the other repositories.
So I will be updating my pom.xml in a couple of days.

**Comment by gwlucastrig** [comment]
The pom.xml is updated and LasReader enhanced to throw an exception when an application tries to use it to read a record from an LAZ file. LasReader can still read the header from an LAZ file (laszip does not compress the header) and is used internally by VertexReaderLas.

To read the point records from an LAZ file, please use VertexReaderLas.
